### ISSUE TITLE
NGINX errors in docker - unable to access GUI

### ISSUE THREAD

**Issue by usafle** [demonrik/HDHR-DVR-docker#3]
Sorry, it's I again.  A new update was pulled down.  No longer able to access the new HDHomeRun WebGUI any longer since the new update and I am seeing these errors in the docker container logs:

```
2022-08-01 14:33:42,751 INFO exited: nginx (exit status 1; not expected)
2022-08-01 14:33:45,757 INFO spawned: 'nginx' with pid 54
2022/08/01 14:33:45 [emerg] 54#54: getpwnam("dvr") failed in /etc/nginx/nginx.conf:4
nginx: [emerg] getpwnam("dvr") failed in /etc/nginx/nginx.conf:4
2022-08-01 14:33:45,787 INFO exited: nginx (exit status 1; not expected)
2022-08-01 14:33:46,789 INFO gave up: nginx entered FATAL state, too many start retries too quickly
```

I'm not sure if this is an "UnRaid specific" issue as it was the last time with the Port:80 issue.  Just wanted to make you aware.

**Comment by demonrik** [comment]
I suspect this is from an update
try removing all but dvr.conf in your /dvrdata volume
I think you need to clear out the old http/php folders in particular so we can rebuild them

**Comment by usafle** [comment]
Ok. I'll be away a few days. I'll attempt this when I return and let you
know.

**Comment by usafle** [comment]
Wow.  It's like you almost know what you are doing.  ;)

Deleting all the folders (minus the TV show recordings) and all the extra log files after stopping the container worked like a charm.  I'm able to access the WebGUI again and no errors in the log.

Another issue you can now _close_


> I suspect this is from an update try removing all but dvr.conf in your /dvrdata volume I think you need to clear out the old http/php folders in particular so we can rebuild them

**Comment by demonrik** [comment]
Glad it fixed your issues.
Yeah - I have to apologize over the permissions and conf files thing.. I went one way, then reversed course which resulted in this pain. Should be stable going forward (fingers crossed)

**Comment by usafle** [comment]
Don't worry, if something else goes wrong I'll be sure to point it out.  ;)
