### ISSUE TITLE
Limit recording space

### ISSUE THREAD

**Issue by DrSpaldo** [demonrik/HDHR-DVR-docker#4]
Hi, I am not sure if I have missed anything or not, but, I cannot seem to find any settings about retention of the recordings. Is there any way to limit how long things are kept or how many episodes are kept?

**Comment by demonrik** [comment]
There is nothing in the container over and above what's included in the record engine provided by Silicondust
i.e. - nothing.
Is up to you to maintain the recordings and/or storage space. Nothing is deleted until you delete.
